# Generated by Django 4.1.1 on 2022-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="imagens",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
