# Generated by Django 4.1.1 on 2022-09-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0002_alter_receita_imagens"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita", old_name="dicas", new_name="ingredientes",
        ),
    ]
